### ISSUE TITLE
⚖️ Register Validator: 

### ISSUE THREAD

**Issue by Bangyan1997** [okp4/networks#54]
### Network Choice

nemeton

### Who are you?

My Name is Rian Dwi Yandi. You can call me yanz. I have experience as a node operator on testnet and mainnet for 2 years in cosmos networks such as: STRIDE, SEI, REBUS, POINT, FORTA, LAMBDA and many others. And I have experience as an ambassador and moderator in several projects such as: 
1. ambassador at flype project. 
2. community manager at zeta market. 
3. moderator at tidefy 
4. moderator in an Indonesian node community named node-X capital. and I also have a telegram community channel and group that talks all about cryptocurrencies. this is my channel https://t.me/airdropsultanindonesia with 8.8k members in it. that's all about me Thank you

### gentx

```json
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Bangyan","identity":"F8C59A135DB2C942","website":"Bangyan#8479","security_contact":"","details":"NODE OPERATOR GMT+7"},"commission":{"rate":"0.050000000000000000","max_rate":"1.000000000000000000","max_change_rate":"0.010000000000000000"},"min_self_delegation":"1","delegator_address":"okp41kuvszp2z63l45e0qm33q3ad47ydq9qhlg3nxye","validator_address":"okp4valoper1kuvszp2z63l45e0qm33q3ad47ydq9qhlakr06c","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"taML4M15wm0HQa453BZr1tVY7P1jK3VxXvd74Vrbrr4="},"value":{"denom":"uknow","amount":"1000000"}}],"memo":"87eaac1197d3191ce9af6bb787d4d6a0c186d58d@10.6.0.4:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AhuM2I/kQGRNQHaGDhKi3B0HkXVDHn9w8jUrOSCRms8F"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""},"tip":null},"signatures":["OY/5Yg4b/ET9ROf3ctjtkvmFJ+pbU2pMzuCzkg0BYtcXJ46w5NwGwA9GPKCbcnUXC8Gp1uJlp8DUiSelwQKJCg=="]}
```

**Comment by amimart** [comment]
We first launch with already identified validators, please stay tuned for the next coming steps 😉
